# Generated by Django 4.2.20 on 2025-06-10 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='deductible_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='paid',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='sub_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.subcategory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='invoice_numb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.keyword'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recurring_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.recurringtransaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sub_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.subcategory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tax',
            field=models.CharField(default='Yes', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.team'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
