# Generated by Django 4.2.20 on 2025-07-12 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='order',
        ),
    ]
