# Generated by Django 4.2.20 on 2025-06-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_transaction_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('personal_vehicle', 'Personal Vehicle'), ('rental_car', 'Rental Car'), ('flight', 'Flight'), ('public_transport', 'Public Transport')], help_text='Used to identify if actual expenses apply', max_length=30, null=True),
        ),
    ]
