# Generated by Django 4.2.20 on 2025-07-03 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_transport_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='finance_tra_date_e22f1b_idx',
            old_name='finance_tra_date_51267a_idx',
        ),
        migrations.AddField(
            model_name='transaction',
            name='old_trans_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(blank=True, choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=10, null=True),
        ),
    ]
