# Generated by Django 4.2.20 on 2025-07-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_rename_finance_tra_date_51267a_idx_finance_tra_date_e22f1b_idx_and_more'),
    ]

    operations = [
    ]
