# Generated by Django 4.2.20 on 2025-07-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_invoice_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='item',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
