# Generated by Django 4.2.20 on 2025-07-13 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_invoiceitem_item_invoiceitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.invoice'),
        ),
    ]
