# Generated by Django 4.2.20 on 2025-07-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20250703_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='old_trans_type',
        ),
    ]
