# Generated by Django 4.2.20 on 2025-04-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_invoice_options_alter_invoiceitem_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
