# Generated by Django 4.2.20 on 2025-07-13 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_transaction_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miles',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.invoice'),
        ),
    ]
