# Generated by Django 4.2.20 on 2025-07-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_transaction_trans_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='trans_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Expense', max_length=10),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
2
