# Generated by Django 4.2.20 on 2025-07-12 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_recurringtransaction_trans_type_delete_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['sub_cat'], 'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tax',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.category'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('personal_vehicle', 'Personal Vehicle'), ('rental_car', 'Rental Car')], help_text='Used to identify if actual expenses apply', max_length=30, null=True),
        ),
    ]
