# Generated by Django 4.2.20 on 2025-07-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='schedule_c_line',
            field=models.CharField(blank=True, help_text="Enter Schedule C line number (e.g., '8', '9', '27a')", max_length=10, null=True),
        ),
    ]
