# Generated by Django 4.2.20 on 2025-05-06 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_invoice_paid_alter_invoice_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='paid',
        ),
    ]
