# Generated by Django 4.2.20 on 2025-05-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_remove_invoice_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.CharField(blank=True, default='No', max_length=100, null=True),
        ),
    ]
