# Generated by Django 4.2.20 on 2025-05-06 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_invoice_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='paid',
        ),
    ]
