# Generated by Django 4.2.20 on 2025-05-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_remove_invoice_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['name']},
        ),
    ]
