# Generated by Django 4.2.20 on 2025-05-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_miles_user_alter_transaction_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deductible_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
