# Generated by Django 4.2.20 on 2025-05-12 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_recurringtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recurring_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='finance.recurringtransaction'),
        ),
    ]
