# Generated by Django 4.2.20 on 2025-05-12 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_transaction_recurring_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.keyword'),
        ),
    ]
