# Generated by Django 4.2.20 on 2025-05-13 23:56

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_alter_transaction_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_numb'], name='finance_inv_invoice_21faaa_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['date'], name='finance_inv_date_1aaab4_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due'], name='finance_inv_due_860b47_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['paid_date'], name='finance_inv_paid_da_03a9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client'], name='finance_inv_client__37a0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['keyword'], name='finance_inv_keyword_1df90a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['service'], name='finance_inv_service_6c695b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='invoice_search_idx'),
        ),
        migrations.AddIndex(
            model_name='miles',
            index=models.Index(fields=['user', 'date'], name='finance_mil_user_id_e82525_idx'),
        ),
        migrations.AddIndex(
            model_name='miles',
            index=models.Index(fields=['mileage_type'], name='finance_mil_mileage_95a41d_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'day', 'active'], name='finance_rec_user_id_d11de8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date', 'trans_type'], name='finance_tra_date_51267a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='finance_tra_user_id_3294c0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['keyword'], name='finance_tra_keyword_d6f638_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='finance_tra_categor_bbdf49_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['sub_cat'], name='finance_tra_sub_cat_01be50_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['invoice_numb'], name='finance_tra_invoice_be4f0a_idx'),
        ),
    ]
