# Generated by Django 4.2.20 on 2025-05-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_invoice_search_vector_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_search_idx',
        ),
    ]
