# Generated by Django 4.2.20 on 2025-05-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_remove_invoice_invoice_search_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='order',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
