# Generated by Django 4.2.20 on 2025-05-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_keyword_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
