# Generated by Django 4.2.20 on 2025-04-20 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50)),
                ('license_date', models.DateField()),
                ('license_image', models.ImageField(upload_to='licenses/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=200)),
                ('date_completed', models.DateField()),
                ('location', models.CharField(default='Online', max_length=100)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('is_annual', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='app.pilotprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
