# Generated by Django 4.2.20 on 2025-04-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pilotprofile_trainingrecord_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilotprofile',
            name='license_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pilotprofile',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AlterField(
            model_name='pilotprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
