# Generated by Django 4.2.20 on 2025-05-03 13:24

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_trainingrecord_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_completed', models.DateField()),
                ('required', models.BooleanField(default=False)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to=app.models.training_certificate_upload_path)),
            ],
            options={
                'ordering': ['-date_completed'],
            },
        ),
        migrations.AlterField(
            model_name='pilotprofile',
            name='license_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pilotprofile',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.license_upload_path),
        ),
        migrations.AlterField(
            model_name='pilotprofile',
            name='license_number',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='TrainingRecord',
        ),
        migrations.AddField(
            model_name='training',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='app.pilotprofile'),
        ),
    ]
