--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.5 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: finance_transaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.finance_transaction (
    id bigint NOT NULL,
    date date NOT NULL,
    date_created date NOT NULL,
    amount numeric(20,2) NOT NULL,
    invoice_numb character varying(500),
    paid character varying(500),
    transaction character varying(500),
    receipt character varying(100),
    tax character varying(500),
    category_id bigint NOT NULL,
    keyword_id bigint,
    sub_cat_id bigint NOT NULL,
    team_id bigint,
    trans_type_id bigint NOT NULL,
    user_id integer NOT NULL,
    deductible_amount numeric(10,2)
);


ALTER TABLE public.finance_transaction OWNER TO postgres;

--
-- Name: finance_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.finance_transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.finance_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: finance_transaction; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.finance_transaction (id, date, date_created, amount, invoice_numb, paid, transaction, receipt, tax, category_id, keyword_id, sub_cat_id, team_id, trans_type_id, user_id, deductible_amount) FROM stdin;
111	2022-06-06	2025-05-04	450.18	22001	yes	Epping	/Volumes/Business/TSP/_FINANCIAL//2023/2022_Receipts/epping_car.png	yes	67	9	23	3	2	1	\N
114	2022-07-21	2025-05-04	424.91	22001	yes	San Francisco	/Volumes/Business?TSP/_FINANCIAL/2023/2022_Receipts/460685486_90141708419_25072022024530.pdf	yes	67	14	23	3	2	1	\N
542	2024-08-19	2025-05-04	319.49	240051	yes	Brainerd Car Rental	None	yes	67	15	23	3	2	1	\N
546	2024-09-09	2025-05-04	160.36	240052	yes	Indy Car	Venture Card	yes	67	16	23	3	2	1	\N
574	2024-11-18	2025-05-04	311.91	240058	yes	Pomona II Car Rental	TC Capital One	yes	67	4	23	3	2	1	\N
37	2025-04-24	2025-04-29	54.39	250105	Yes	Charlotte I Gas		Yes	69	6	27	3	2	1	\N
34	2025-04-25	2025-04-29	65.26	250105	Yes	Charlotte I Gas		Yes	69	6	27	3	2	1	\N
40	2025-04-29	2025-04-29	68.71	250105	Yes	Charlotte I Gas		Yes	69	6	27	3	2	1	\N
36	2025-04-24	2025-04-29	36.18	250105	Yes	Charlotte I Meals		Yes	10	6	26	3	2	1	\N
103	2025-03-10	2025-05-03	28.78	250101	Yes	Gainesville Gas	receipts/Scanned_Document.pdf	Yes	69	1	27	3	2	1	\N
67	2025-04-24	2025-05-01	3250.00	250101	4/25/2025	Gainesville Invoice		Yes	7	1	19	3	1	1	\N
35	2025-04-24	2025-04-29	19.72	250105	Yes	Charlotte I Meals		Yes	10	6	26	3	2	1	\N
455	2024-05-08	2025-05-04	315.00	240999	yes	Mavic 3 Repair	PNC Debit	yes	35	100	6	3	2	1	\N
68	2025-04-24	2025-05-01	3250.00	250102	4/25/2025	Phoenix Invoice		Yes	7	2	19	3	1	1	\N
101	2025-03-08	2025-05-03	10.63	250101	Yes	Gainesville Meal	receipts/Gainsville_Meal.pdf	Yes	10	1	26	3	2	1	\N
102	2025-03-19	2025-05-03	29.15	250102	Yes	Phoenix Meal	receipts/Phoenix-Meal_1.pdf	Yes	10	2	26	3	2	1	\N
39	2025-04-27	2025-04-29	397.62	250105	Yes	Charlotte I Hotel		Yes	69	6	25	3	2	1	\N
481	2024-05-20	2025-05-04	50.08	240033	yes	240033	/volumes/TSP/_FINANCIAL/2024/Receipts/240031_NHRA_Chicago_Gas_2.pdf	yes	69	8	27	3	2	1	\N
105	2025-04-28	2025-05-03	19.93	250105	Yes	Charlotte Meal	receipts/250105_Charlotte_I_Meals_b.pdf	Yes	10	6	26	3	2	1	\N
108	2022-01-23	2025-05-04	36.00	22001	yes	Epping - Parking	Volumes/Business/TSP/_FINANCIAL//2023/2022_Receipts/IMG_0659 3.jpeg	yes	69	9	28	3	2	1	\N
38	2025-04-28	2025-04-29	105.84	250105	Yes	Charlotte I Hotel Beckley, WV		Yes	69	6	25	3	2	1	\N
513	2024-06-26	2025-05-04	44.19	240047	yes	Travel: Gas	Chase Business Card	yes	69	12	27	3	2	1	\N
100	2025-04-01	2025-05-03	868.00	250103	Yes	Pomona I Hotel Receipt	receipts/Pomona_Hotel.pdf	Yes	69	3	25	3	2	1	\N
109	2022-03-08	2025-05-04	1400.00	22001	yes	Fatheadz Pay	Check to PNC	yes	7	34	19	3	1	1	\N
110	2022-05-19	2025-05-04	2073.98	22001	yes	Fatheadz Pay	PNC	yes	7	34	19	3	1	1	\N
115	2022-07-27	2025-05-04	469.94	22001	yes	Fatheadz Pay	PNC 	yes	7	34	19	3	1	1	\N
104	2025-04-14	2025-05-03	533.30	250104	Yes	Vegas I Hotel	receipts/Vegas_I_Hotel.pdf	Yes	69	5	25	3	2	1	\N
384	2024-01-14	2025-05-04	17.00	240999	yes	Website - Heroku	None	yes	4	100	14	1	2	1	\N
133	2023-02-01	2025-05-04	29.00	23002	yes	Udemy		yes	8	100	21	1	2	1	\N
121	2023-01-01	2025-05-04	29.00	23002	yes	Udemy		yes	8	100	21	1	2	1	\N
125	2023-01-14	2025-05-04	15.36	23002	yes	Website - Heroku	None	yes	8	100	34	4	2	1	\N
229	2023-07-01	2025-05-04	99.38	23002	yes	iPad		yes	35	100	5	1	2	1	\N
396	2024-02-15	2025-05-04	99.38	240999	yes	iPad		yes	35	100	5	1	2	1	\N
438	2024-04-16	2025-05-04	1389.93	240999	yes	Mavic 3 Classic Drone Kit - Roberts	/volumes/TSP/_FINANCIAL/2024/Receipts/mavic_3_classic.pdf	yes	35	100	1	3	2	1	\N
122	2023-01-01	2025-05-04	17.00	23002	yes	Heroku		yes	8	100	34	1	2	1	\N
633	2024-11-22	2025-05-04	284.20	September	yes	Affirm - Canon R5 Purchase	Posted on the 12th	yes	35	100	4	2	2	1	\N
123	2023-01-01	2025-05-04	109.99	23002	yes	FirstNet		yes	11	100	29	1	2	1	\N
485	2024-06-01	2025-05-04	29.99	240999	yes	Adobe CC	PNC Debit	yes	4	100	12	1	2	1	\N
273	2023-08-20	2025-05-04	9.99	23002	yes	Apple iCloud	None	yes	4	100	12	1	2	1	\N
162	2023-04-01	2025-05-04	74.40	23002	yes	Cell Phone		yes	35	100	3	1	2	1	\N
258	2023-08-01	2025-05-04	250.00	23002	yes	Drone Purchase		yes	35	100	1	3	2	1	\N
554	2024-09-25	2025-05-04	81.05	240999	yes	DJI Controller Repair - HDMI Port	Chase Business	yes	35	100	6	3	2	1	\N
112	2022-07-07	2025-05-04	146.00	22001	yes	Denver	/Volumes/Business/TSP/2023/2022_Receipts/Denver Hotel.pdf	yes	69	35	25	3	2	1	\N
113	2022-07-11	2025-05-04	219.00	22001	yes	Sonoma 	/Volumes/Business/TSP/_Financial/2023/2022_Receipts/sonoma_hotel.pdf	yes	69	14	25	3	2	1	\N
272	2023-08-16	2025-05-04	13.36	23002	yes	Paddle.net	None	yes	4	100	12	4	2	1	\N
146	2023-03-01	2025-05-04	13.36	23002	yes	Microsoft 365		yes	4	100	12	1	2	1	\N
350	2023-11-14	2025-05-04	17.00	23002	yes	Website - Heroku	None	yes	4	100	14	4	2	1	\N
153	2023-03-08	2025-05-04	575.92	23002	yes	Gainsville - Fatheadz	None	yes	67	1	23	3	2	1	\N
386	2024-01-24	2025-05-04	82.18	240999	yes	Samsung - Monitor	None	yes	35	100	5	1	2	1	\N
483	2024-06-01	2025-05-04	99.38	240999	yes	iPad	PNC Debit	yes	35	100	5	1	2	1	\N
160	2023-03-31	2025-05-04	191.25	23002	yes	Pomona I	/Volumes/Business/TSP/_FINANCIAL//2023/2022_Receipts/Pomona_Car.pdf	yes	67	3	23	3	2	1	\N
406	2024-03-21	2025-05-04	74.40	240999	yes	Cell Phone		yes	35	100	3	1	2	1	\N
184	2023-05-01	2025-05-04	29.00	23002	yes	Udemy		yes	8	100	21	1	2	1	\N
138	2023-02-14	2025-05-04	15.36	23002	yes	Website - Heroku	None	yes	8	100	34	4	2	1	\N
190	2023-05-14	2025-05-04	17.00	23002	yes	Website - Heroku	None	yes	8	100	34	4	2	1	\N
516	2024-06-27	2025-05-04	36.94	240042	yes	NHRA Virginia	Captial One - Red	yes	69	37	27	3	2	1	\N
543	2024-08-19	2025-05-04	63.10	240051	yes	Brainerd Gas	Chase Business	yes	69	15	27	3	2	1	\N
168	2023-04-01	2025-05-04	17.00	23002	yes	Heroku		yes	8	100	34	1	2	1	\N
155	2023-03-14	2025-05-04	15.36	23002	yes	Website - Heroku	None	yes	8	100	34	4	2	1	\N
135	2023-02-01	2025-05-04	17.00	23002	yes	Heroku		yes	8	100	34	1	2	1	\N
424	2024-04-10	2025-05-04	74.40	240999	yes	Cell Phone		yes	35	100	3	1	2	1	\N
547	2024-09-09	2025-05-04	38.89	240052	yes	Indy Gas	Venture Card	yes	69	16	27	3	2	1	\N
116	2023-01-01	2025-05-04	99.38	23002	yes	iPad		yes	35	100	5	1	2	1	\N
170	2023-04-01	2025-05-04	128.00	23002	yes	Leaseville		yes	35	100	5	1	2	1	\N
549	2024-09-15	2025-05-04	58.72	240053	yes	Reading	Rose Card	yes	69	17	27	3	2	1	\N
462	2024-05-13	2025-05-04	99.38	240999	yes	iPad		yes	35	100	5	1	2	1	\N
276	2023-08-24	2025-05-04	82.18	23002	yes	Samsung - Monitor	None	yes	35	100	5	1	2	1	\N
173	2023-04-14	2025-05-04	15.36	23002	yes	Website - Heroku	None	yes	8	100	34	4	2	1	\N
149	2023-03-01	2025-05-04	17.00	23002	yes	Heroku		yes	8	100	34	1	2	1	\N
166	2023-04-01	2025-05-04	29.00	23002	yes	Udemy		yes	8	100	21	1	2	1	\N
345	2023-11-01	2025-05-04	128.00	23002	yes	Leaseville		yes	35	100	5	1	2	1	\N
550	2024-09-16	2025-05-04	37.56	250053	yes	NHRA Reading	Venture Card	yes	69	17	27	3	2	1	\N
551	2024-09-19	2025-05-04	29.75	250043	yes	Reading	Chase Business	yes	69	17	27	3	2	1	\N
147	2023-03-01	2025-05-04	29.00	23002	yes	Udemy		yes	8	100	21	1	2	1	\N
159	2023-03-29	2025-05-04	49.00	23002	yes	Coursera	None	yes	8	100	21	4	2	1	\N
186	2023-05-01	2025-05-04	17.00	23002	yes	Heroku		yes	8	100	34	1	2	1	\N
605	2024-11-22	2025-05-04	82.18	September	yes	Samsung Monitor - Affirm	Posted on the 24th	yes	35	100	5	4	2	1	\N
724	2024-03-14	2025-05-08	85.79	240015	Yes	Gainesville Gas		Yes	69	1	27	3	2	1	\N
473	2024-05-16	2025-05-04	239.00	240999	yes	DJI Care Refresh for Mavic 3 Pro	PNC Debit Card	yes	35	100	1	3	2	1	\N
180	2023-05-01	2025-05-04	74.40	23002	yes	Cell Phone		yes	35	100	3	1	2	1	\N
725	2024-05-08	2025-05-08	29.99	240018	Yes	Phoenix Gas		Yes	69	2	27	3	2	1	\N
337	2023-11-01	2025-05-04	74.40	23002	yes	Cell Phone		yes	35	100	3	1	2	1	\N
348	2023-11-03	2025-05-04	250.00	23002	yes	Drone Purchase		yes	35	100	1	3	2	1	\N
178	2023-04-29	2025-05-04	49.00	23002	yes	Coursera	None	yes	8	100	21	4	2	1	\N
169	2023-04-01	2025-05-04	109.99	23002	yes	FirstNet		yes	11	100	29	1	2	1	\N
189	2023-05-01	2025-05-04	176.84	23002	yes	The Hartford		yes	2	100	8	1	2	1	\N
726	2024-04-18	2025-05-08	61.87	240019	Yes	Vegas I Gas		Yes	69	5	27	3	2	1	\N
375	2023-12-24	2025-05-04	82.18	23002	yes	Samsung - Monitor	None	yes	35	100	5	1	2	1	\N
154	2023-03-10	2025-05-04	284.56	23002	yes	Gainsville	/Volumes/Business/TSP/_FINANCIAL/2023/2022_Receipts/Gainsville Hotel.pdf	yes	69	1	25	3	2	1	\N
172	2023-04-03	2025-05-04	36.00	23002	yes	Gainsville Parking	/Volumes/Business/TSP/_FINANCIAL//2023/2022_Receipts/indianapolis.pdf	yes	69	1	28	3	2	1	\N
152	2023-03-01	2025-05-04	176.84	23002	yes	The Hartford		yes	2	100	8	1	2	1	\N
136	2023-02-01	2025-05-04	109.99	23002	yes	FirstNet		yes	11	100	29	1	2	1	\N
150	2023-03-01	2025-05-04	109.99	23002	yes	FirstNet		yes	11	100	29	1	2	1	\N
238	2023-07-01	2025-05-04	128.00	23002	yes	Leaseville		yes	35	100	5	1	2	1	\N
399	2024-02-15	2025-05-04	74.40	240999	yes	Cell Phone		yes	35	100	3	1	2	1	\N
626	2024-11-22	2025-05-04	99.38	September	yes	FirstNet iPad Purchase	Posted on the 18th	yes	35	100	3	1	2	1	\N
268	2023-08-01	2025-05-04	128.00	23002	yes	Leaseville		yes	35	100	5	1	2	1	\N
518	2024-07-01	2025-05-04	99.38	240999	yes	iPad	PNC Debit	yes	35	100	5	1	2	1	\N
187	2023-05-01	2025-05-04	109.99	23002	yes	FirstNet		yes	11	100	29	1	2	1	\N
171	2023-04-01	2025-05-04	176.84	23002	yes	The Hartford		yes	2	100	8	1	2	1	\N
475	2024-05-16	2025-05-04	230.54	240999	yes	DJI RC Pro Controller	Chase Business Card	yes	35	100	1	3	2	1	\N
226	2023-06-30	2025-05-04	32.00	23002	yes	Denver	None	yes	69	35	24	3	2	1	\N
641	2024-11-26	2025-05-04	1323.76	249999	yes	Canon EOS R5	Chase Business Debit	yes	35	100	4	2	2	1	\N
638	2024-11-22	2025-05-04	128.00	October	yes	Computer Speakers/Lights	Posted on the 11th & 13th	yes	35	100	5	1	2	1	\N
227	2023-06-30	2025-05-04	127.00	23002	yes	Checked Bag	None	yes	69	35	24	3	2	1	\N
247	2023-07-26	2025-05-04	132.00	23002	yes		None	yes	69	14	24	3	2	1	\N
225	2023-06-29	2025-05-04	49.00	23002	yes	Coursera	None	yes	8	100	21	4	2	1	\N
252	2023-07-29	2025-05-04	49.00	23002	yes	Coursera	None	yes	8	100	21	4	2	1	\N
236	2023-07-01	2025-05-04	17.00	23002	yes	Heroku		yes	8	100	34	1	2	1	\N
482	2024-05-30	2025-05-04	230.54	240999	yes	DJI RC Pro Controller	Chase Business Card	yes	35	100	1	3	2	1	\N
248	2023-07-26	2025-05-04	52.68	23002	yes		None	yes	69	14	24	3	2	1	\N
282	2023-09-01	2025-05-04	74.40	23002	yes	Cell Phone		yes	35	100	3	1	2	1	\N
200	2023-06-01	2025-05-04	74.40	23002	yes	Cell Phone		yes	35	100	3	1	2	1	\N
216	2023-06-26	2025-05-04	4.75	23002	yes	Norwalk, Toll	None	yes	69	12	28	3	2	1	\N
311	2023-10-01	2025-05-04	74.40	23002	yes	Cell Phone		yes	35	100	3	1	2	1	\N
329	2023-10-24	2025-05-04	82.18	23002	yes	Samsung - Monitor	None	yes	35	100	5	1	2	1	\N
195	2023-05-29	2025-05-04	49.00	23002	yes	Coursera	None	yes	8	100	21	4	2	1	\N
206	2023-06-01	2025-05-04	17.00	23002	yes	Heroku		yes	8	100	34	1	2	1	\N
210	2023-06-14	2025-05-04	17.00	23002	yes	Website - Heroku	None	yes	8	100	34	4	2	1	\N
217	2023-06-26	2025-05-04	7.14	23002	yes		None	yes	10	12	26	3	2	1	\N
218	2023-06-26	2025-05-04	1500.00	23002	yes	NHRA	None	yes	7	12	19	3	1	1	\N
219	2023-06-26	2025-05-04	248.00	23002	yes	Aviation Insurance	None	yes	2	12	7	3	2	1	\N
221	2023-06-28	2025-05-04	1250.00	23002	yes	NHRA		yes	7	34	19	3	1	1	\N
222	2023-06-28	2025-05-04	1250.00	23002	yes	NHRA		yes	7	34	19	3	1	1	\N
682	2022-02-04	2025-05-04	128.00	23002	yes	Leaseville		yes	35	100	5	1	2	1	\N
630	2024-11-22	2025-05-04	99.38	October	yes	FirstNet iPad Purchase	Posted on the 18th	yes	35	100	3	1	2	1	\N
234	2023-07-01	2025-05-04	29.00	23002	yes	Udemy		yes	8	100	21	1	2	1	\N
242	2023-07-14	2025-05-04	17.00	23002	yes	Website - Heroku	None	yes	8	100	34	4	2	1	\N
204	2023-06-01	2025-05-04	29.00	23002	yes	Udemy		yes	8	100	21	1	2	1	\N
401	2024-02-24	2025-05-04	82.18	240999	yes	Samsung - Monitor	None	yes	35	100	5	1	2	1	\N
161	2023-04-01	2025-05-04	99.38	23002	yes	iPad		yes	35	100	5	1	2	1	\N
228	2023-06-30	2025-05-04	295.26	23002	yes	The Hartford Insurance	None	yes	2	100	8	1	2	1	\N
209	2023-06-01	2025-05-04	176.84	23002	yes	The Hartford		yes	2	100	8	1	2	1	\N
237	2023-07-01	2025-05-04	109.99	23002	yes	FirstNet		yes	11	100	29	1	2	1	\N
253	2023-07-30	2025-05-04	144.86	23002	yes	The Hartford Insurance	None	yes	2	100	8	1	2	1	\N
197	2023-05-30	2025-05-04	144.86	23002	yes	The Hartford Insurance	None	yes	2	100	8	1	2	1	\N
250	2023-07-27	2025-05-04	23.58	23002	yes		None	yes	10	14	26	3	2	1	\N
251	2023-07-27	2025-05-04	25.16	23002	yes		None	yes	10	14	26	3	2	1	\N
255	2023-08-01	2025-05-04	1250.00	23002	yes	NHRA		yes	7	34	19	3	1	1	\N
256	2023-08-01	2025-05-04	1250.00	23002	yes	NHRA		yes	7	34	19	3	1	1	\N
207	2023-06-01	2025-05-04	109.99	23002	yes	FirstNet		yes	11	100	29	1	2	1	\N
239	2023-07-01	2025-05-04	176.84	23002	yes	The Hartford		yes	2	100	8	1	2	1	\N
254	2023-07-30	2025-05-04	156.00	23002	yes	Aviation Insurance	None	yes	2	100	7	3	2	1	\N
198	2023-05-30	2025-05-04	156.00	23002	yes	Aviation Insurance	None	yes	2	100	7	3	2	1	\N
296	2023-09-13	2025-05-04	30.00	23002	yes	Reading	None	yes	69	17	24	3	2	1	\N
278	2023-08-29	2025-05-04	49.00	23002	yes	Coursera	None	yes	8	100	21	4	2	1	\N
286	2023-09-01	2025-05-04	29.00	23002	yes	Udemy		yes	8	100	21	1	2	1	\N
266	2023-08-01	2025-05-04	17.00	23002	yes	Heroku		yes	8	100	34	1	2	1	\N
235	2023-07-01	2025-05-04	82.08	23002	yes	Samsung		yes	35	100	5	1	2	1	\N
117	2023-01-01	2025-05-04	74.40	23002	yes	Cell Phone		yes	35	100	3	1	2	1	\N
188	2023-05-01	2025-05-04	128.00	23002	yes	Leaseville		yes	35	100	5	1	2	1	\N
257	2023-08-01	2025-05-04	250.00	23002	yes	Drone Purchase		yes	35	100	1	3	2	1	\N
264	2023-08-01	2025-05-04	29.00	23002	yes	Udemy		yes	8	100	21	1	2	1	\N
315	2023-10-01	2025-05-04	29.00	23002	yes	Udemy		yes	8	100	21	1	2	1	\N
307	2023-09-29	2025-05-04	49.00	23002	yes	Coursera	None	yes	8	100	21	4	2	1	\N
267	2023-08-01	2025-05-04	109.99	23002	yes	FirstNet		yes	11	100	29	1	2	1	\N
274	2023-08-23	2025-05-04	1298.02	23002	yes	NHRA		yes	7	34	19	3	1	1	\N
306	2023-09-26	2025-05-04	128.00	23002	yes	Leaseville	None	yes	35	100	5	1	2	1	\N
240	2023-07-07	2025-05-04	35.36	23002	yes	DJI Mini 3 Pro Batterie	None	yes	35	100	1	3	2	1	\N
376	2023-12-26	2025-05-04	128.00	23002	yes	Leaseville	None	yes	35	100	5	1	2	1	\N
309	2023-09-30	2025-05-04	156.00	23002	yes	Aviation Insurance	None	yes	2	100	7	3	2	1	\N
289	2023-09-01	2025-05-04	109.99	23002	yes	FirstNet		yes	11	100	29	1	2	1	\N
269	2023-08-01	2025-05-04	176.84	23002	yes	The Hartford		yes	2	100	8	1	2	1	\N
561	2024-09-30	2025-05-04	267.49	249999	yes	OWC Enclosure 2	B & H	yes	35	100	3	1	2	1	\N
280	2023-08-30	2025-05-04	156.00	23002	yes	Aviation Insurance	None	yes	2	100	7	3	2	1	\N
507	2024-06-24	2025-05-04	230.54	240999	yes	DJI RC Pro Controller	Chase Business Card	yes	35	100	1	3	2	1	\N
634	2024-11-22	2025-05-04	284.20	October	yes	Affirm - Canon R5 Purchase	Posted on the 12th	yes	35	100	4	2	2	1	\N
292	2023-09-05	2025-05-04	1250.00	23002	yes	NHRA		yes	7	34	19	3	1	1	\N
293	2023-09-05	2025-05-04	1250.00	23002	yes	NHRA		yes	7	34	19	3	1	1	\N
279	2023-08-30	2025-05-04	144.86	23002	yes	The Hartford Insurance	None	yes	2	100	8	1	2	1	\N
318	2023-10-01	2025-05-04	109.99	23002	yes	FirstNet		yes	11	100	29	1	2	1	\N
308	2023-09-30	2025-05-04	144.86	23002	yes	The Hartford Insurance	None	yes	2	100	8	1	2	1	\N
300	2023-09-19	2025-05-04	1310.19	23002	yes	NHRA		yes	7	34	19	3	1	1	\N
291	2023-09-01	2025-05-04	176.84	23002	yes	The Hartford		yes	2	100	8	1	2	1	\N
304	2023-09-25	2025-05-04	1250.00	23002	yes	NHRA		yes	7	34	19	3	1	1	\N
632	2024-11-22	2025-05-04	284.20	August	yes	Affirm - Canon R5 Purchase	Posted on the 12th	yes	35	100	4	2	2	1	\N
196	2023-05-29	2025-05-04	72.39	23002	yes	Amazon Order-DJI Controller	None	yes	35	100	1	3	2	1	\N
281	2023-09-01	2025-05-04	99.38	23002	yes	iPad		yes	35	100	5	1	2	1	\N
642	2024-11-26	2025-05-04	763.47	249999	yes	Samsung Monitor	Chase Business Debit	yes	35	100	5	1	2	1	\N
259	2023-08-01	2025-05-04	99.38	23002	yes	iPad		yes	35	100	5	1	2	1	\N
468	2024-05-13	2025-05-04	82.08	240999	yes	Samsung		yes	35	100	5	1	2	1	\N
622	2024-11-22	2025-05-04	99.38	August	yes	FirstNet iPad Purchase	Posted on the 18th	yes	35	100	3	1	2	1	\N
310	2023-10-01	2025-05-04	99.38	23002	yes	iPad		yes	35	100	5	1	2	1	\N
213	2023-06-18	2025-05-04	187.82	23002	yes	Amazon order -Tent	None	yes	35	100	2	3	2	1	\N
677	2025-02-06	2025-05-04	99.38	Monthly	yes	Verizon iPad	Posted on the 7th	yes	35	100	3	1	2	1	\N
321	2023-10-02	2025-05-04	1374.00	23002	yes	NHRA		yes	7	34	19	3	1	1	\N
333	2023-10-29	2025-05-04	49.00	23002	yes	Coursera	None	yes	8	100	21	4	2	1	\N
341	2023-11-01	2025-05-04	29.00	23002	yes	Udemy		yes	8	100	21	1	2	1	\N
365	2023-12-01	2025-05-04	29.00	23002	yes	Udemy		yes	8	100	21	1	2	1	\N
326	2023-10-17	2025-05-04	1309.26	23002	yes	NHRA		yes	7	34	19	3	1	1	\N
377	2023-12-29	2025-05-04	49.00	23002	yes	Coursera	None	yes	8	100	21	4	2	1	\N
330	2023-10-26	2025-05-04	17.32	23002	yes			yes	10	34	26	3	2	1	\N
331	2023-10-26	2025-05-04	40.07	23002	yes			yes	10	34	26	3	2	1	\N
249	2023-07-26	2025-05-04	128.00	23002	yes	Leaseville	None	yes	35	100	5	1	2	1	\N
398	2024-02-15	2025-05-04	99.38	240999	yes	iPad		yes	35	100	5	1	2	1	\N
366	2023-12-01	2025-05-04	82.08	23002	yes	Samsung		yes	35	100	5	1	2	1	\N
357	2023-11-29	2025-05-04	49.00	23002	yes	Coursera	None	yes	8	100	21	4	2	1	\N
346	2023-11-01	2025-05-04	176.84	23002	yes	The Hartford		yes	2	100	8	1	2	1	\N
370	2023-12-01	2025-05-04	176.84	23002	yes	The Hartford		yes	2	100	8	1	2	1	\N
489	2024-06-01	2025-05-04	82.08	240999	yes	Samsung	PNC Debit	yes	35	100	5	1	2	1	\N
378	2023-12-30	2025-05-04	144.86	23002	yes	The Hartford Insurance	None	yes	2	100	8	1	2	1	\N
635	2024-11-22	2025-05-04	128.00	July	yes	Computer Speakers/Lights	Posted on the 11th & 13th	yes	35	100	5	1	2	1	\N
397	2024-02-15	2025-05-04	74.40	240999	yes	Cell Phone		yes	35	100	3	1	2	1	\N
347	2023-11-03	2025-05-04	1281.70	23002	yes	NHRA		yes	7	34	19	3	1	1	\N
349	2023-11-14	2025-05-04	1298.06	23002	yes	NHRA		yes	7	34	19	3	1	1	\N
334	2023-10-30	2025-05-04	144.86	23002	yes	The Hartford Insurance	None	yes	2	100	8	1	2	1	\N
379	2023-12-30	2025-05-04	156.00	23002	yes	Aviation Insurance	None	yes	2	100	7	3	2	1	\N
320	2023-10-01	2025-05-04	176.84	23002	yes	The Hartford		yes	2	100	8	1	2	1	\N
368	2023-12-01	2025-05-04	109.99	23002	yes	FirstNet		yes	11	100	29	1	2	1	\N
151	2023-03-01	2025-05-04	128.00	23002	yes	Leaseville		yes	35	100	5	1	2	1	\N
604	2024-11-22	2025-05-04	82.18	August	yes	Samsung Monitor - Affirm	Posted on the 24th	yes	35	100	5	4	2	1	\N
179	2023-05-01	2025-05-04	99.38	23002	yes	iPad		yes	35	100	5	1	2	1	\N
344	2023-11-01	2025-05-04	109.99	23002	yes	FirstNet		yes	11	100	29	1	2	1	\N
335	2023-10-30	2025-05-04	156.00	23002	yes	Aviation Insurance	None	yes	2	100	7	3	2	1	\N
358	2023-11-30	2025-05-04	144.86	23002	yes	The Hartford Insurance	None	yes	2	100	8	1	2	1	\N
305	2023-09-25	2025-05-04	250.00	23002	yes	Drone Purchase		yes	35	100	1	3	2	1	\N
359	2023-11-30	2025-05-04	156.00	23002	yes	Aviation Insurance	None	yes	2	100	7	3	2	1	\N
636	2024-11-22	2025-05-04	128.00	August	yes	Computer Speakers/Lights	Posted on the 11th & 13th	yes	35	100	5	1	2	1	\N
205	2023-06-01	2025-05-04	82.08	23002	yes	Samsung		yes	35	100	5	1	2	1	\N
361	2023-12-01	2025-05-04	74.40	23002	yes	Cell Phone		yes	35	100	3	1	2	1	\N
681	2023-10-02	2025-05-04	82.08	23002	yes	Samsung		yes	35	100	5	1	2	1	\N
303	2023-09-24	2025-05-04	82.18	23002	yes	Samsung - Monitor	None	yes	35	100	5	1	2	1	\N
631	2024-11-22	2025-05-04	284.20	July	yes	Affirm - Canon R5 Purchase	Posted on the 12th	yes	35	100	4	2	2	1	\N
351	2023-11-14	2025-05-04	13.38	23002	yes	Office 365	None	yes	4	100	12	1	2	1	\N
295	2023-09-05	2025-05-04	250.00	23002	yes	Drone Purchase		yes	35	100	1	3	2	1	\N
402	2024-02-28	2025-05-04	49.00	240999	yes	Coursera	None	yes	8	100	21	1	2	1	\N
484	2024-06-01	2025-05-04	74.40	240999	yes	Cell Phone	PNC Debit	yes	35	100	3	1	2	1	\N
387	2024-01-30	2025-05-04	49.00	240999	yes	Coursera	None	yes	8	100	21	1	2	1	\N
410	2024-03-21	2025-05-04	29.00	240999	yes	Udemy		yes	8	100	21	1	2	1	\N
405	2024-03-21	2025-05-04	30.00	240016	yes	Pomona I		yes	69	3	24	3	2	1	\N
107	2022-02-04	2025-05-04	128.00	23002	yes	Leaseville		yes	35	100	5	1	2	1	\N
134	2023-02-01	2025-05-04	82.08	23002	yes	Samsung		yes	35	100	5	1	2	1	\N
428	2024-04-10	2025-05-04	29.00	240999	yes	Udemy		yes	8	100	21	1	2	1	\N
220	2023-06-26	2025-05-04	128.00	23002	yes	Leaseville	None	yes	35	100	5	1	2	1	\N
431	2024-04-10	2025-05-04	109.99	240999	yes	FirstNet		yes	11	100	29	1	2	1	\N
471	2024-05-13	2025-05-04	128.00	240999	yes	Leaseville		yes	35	100	5	1	2	1	\N
433	2024-04-10	2025-05-04	143.61	240999	yes	The Hartford		yes	2	100	8	1	2	1	\N
417	2024-03-22	2025-05-04	49.78	240016	yes	Pomona I	/Volumes/Business/TSP/_Financial/2024/Invoices/240016_NHRA.pdf	yes	69	3	27	3	2	1	\N
421	2024-04-08	2025-05-04	27.99	240018	yes	Phoenix	/volumes/TSP/_FINANCIAL/2024/Receipts/PHX_Gas.jpeg	yes	69	2	27	3	2	1	\N
434	2024-04-14	2025-05-04	61.87	240019	yes	Vegas I	Capital One CC	yes	69	5	27	3	2	1	\N
383	2024-01-12	2025-05-04	42.79	240999	yes	LinkedIn	None	yes	3	100	22	1	2	1	42.79
415	2024-03-21	2025-05-04	161.36	240999	yes	The Hartford		yes	2	100	8	1	2	1	\N
394	2024-02-12	2025-05-04	42.79	240999	yes	LinkedIn	None	yes	3	100	22	1	2	1	42.79
322	2023-10-02	2025-05-04	250.00	23002	yes	Drone Purchase		yes	35	100	1	3	2	1	\N
223	2023-06-28	2025-05-04	250.00	23002	yes	Drone Purchase		yes	35	100	1	3	2	1	\N
352	2023-11-14	2025-05-04	250.00	23002	yes	Drone Purchase	None	yes	35	100	1	3	2	1	\N
435	2024-04-15	2025-05-04	74.04	240019	yes	Vegas I - Flights	Capital One CC	yes	69	5	24	3	34	1	\N
436	2024-04-16	2025-05-04	25.30	240019	yes	Vegas I - Meals	Capital One CC	yes	10	5	26	3	34	1	12.65
390	2024-02-05	2025-05-04	5.00	240999	yes	FAA Drone Registration	None	yes	3	100	36	3	2	1	\N
413	2024-03-21	2025-05-04	109.99	240999	yes	FirstNet		yes	11	100	29	1	2	1	\N
403	2024-02-28	2025-05-04	144.86	240999	yes	The Hartford Insurance	None	yes	2	100	8	1	2	1	\N
287	2023-09-01	2025-05-04	82.08	23002	yes	Samsung		yes	35	100	5	1	2	1	\N
437	2024-04-16	2025-05-04	44.48	240019	yes	Vegas I - Meals	Capital One CC	yes	10	5	26	3	34	1	22.24
404	2024-03-07	2025-05-04	400.00	240999	yes	DRE Portraits	PNC Deposit	yes	7	100	20	2	1	1	\N
524	2024-07-01	2025-05-04	82.08	240999	yes	Samsung	PNC Debit	yes	35	100	5	1	2	1	\N
327	2023-10-17	2025-05-04	250.00	23002	yes	Drone Purchase		yes	35	100	1	3	2	1	\N
416	2024-03-22	2025-05-04	10.72	240016	yes	Pomona I	Blaze CC	yes	10	3	26	3	2	1	\N
418	2024-03-23	2025-05-04	13.20	240016	yes	Pomona I	Blaze CC	yes	10	3	26	3	2	1	\N
422	2024-04-10	2025-05-04	1335.79	240015	yes	Gainsville	PNC Deposit	yes	7	100	19	3	1	1	\N
420	2024-04-08	2025-05-04	28.59	240018	yes	Phoenix	/volumes/TSP/_FINANCIAL/2024/Receipts/PHX_Meal.jpeg	yes	10	2	26	3	2	1	\N
167	2023-04-01	2025-05-04	82.08	23002	yes	Samsung		yes	35	100	5	1	2	1	\N
388	2024-01-30	2025-05-04	144.86	240999	yes	The Hartford Insurance	None	yes	2	100	8	1	2	1	\N
277	2023-08-26	2025-05-04	128.00	23002	yes	Leaseville	None	yes	35	100	5	1	2	1	\N
290	2023-09-01	2025-05-04	128.00	23002	yes	Leaseville		yes	35	100	5	1	2	1	\N
356	2023-11-26	2025-05-04	128.00	23002	yes	Leaseville	None	yes	35	100	5	1	2	1	\N
494	2024-06-03	2025-05-04	199.00	249999	yes	Canon 16mm Lens	B & H	yes	35	100	4	2	2	1	\N
391	2024-02-09	2025-05-04	128.00	240999	yes	Leaseville	None	yes	35	100	5	1	2	1	\N
265	2023-08-01	2025-05-04	82.08	23002	yes	Samsung		yes	35	100	5	1	2	1	\N
342	2023-11-01	2025-05-04	82.08	23002	yes	Samsung		yes	35	100	5	1	2	1	\N
467	2024-05-13	2025-05-04	29.00	240999	yes	Udemy		yes	8	100	21	1	2	1	\N
443	2024-04-23	2025-05-04	1299.78	240016	yes	Pomona I		yes	7	3	19	3	1	1	\N
454	2024-05-06	2025-05-04	54.00	240999	yes	Serge Remelle Software Training	PNC Debit	yes	8	100	21	2	2	1	\N
414	2024-03-21	2025-05-04	128.00	240999	yes	Leaseville		yes	35	100	5	1	2	1	\N
199	2023-06-01	2025-05-04	99.38	23002	yes	iPad		yes	35	100	5	1	2	1	\N
488	2024-06-01	2025-05-04	29.00	240999	yes	Udemy	PNC Debit	yes	8	100	21	1	2	1	\N
246	2023-07-24	2025-05-04	82.18	23002	yes	Samsung - Monitor	None	yes	35	100	5	1	2	1	\N
460	2024-05-09	2025-05-04	1277.99	240018	yes	Phoenix	Deposited to PNC	yes	7	2	19	3	1	1	\N
369	2023-12-01	2025-05-04	128.00	23002	yes	Leaseville		yes	35	100	5	1	2	1	\N
461	2024-05-10	2025-05-04	397.00	240999	yes	Drone Launch Academy	PNC Debit Card	yes	8	100	21	3	2	1	\N
491	2024-06-01	2025-05-04	109.99	240999	yes	FirstNet	PNC Debit	yes	11	100	29	1	2	1	\N
493	2024-06-01	2025-05-04	143.61	240999	yes	The Hartford	Chase Debit	yes	2	100	8	1	2	1	\N
128	2023-02-01	2025-05-04	99.38	23002	yes	iPad		yes	35	100	5	1	2	1	\N
440	2024-04-17	2025-05-04	17.68	240018	yes	Phoenix - Meals	Capital One CC	yes	10	2	26	3	34	1	\N
459	2024-05-09	2025-05-04	175.00	240027	yes	Senior Portraits - Langemeier	file:///Volumes/Business/TSP/_FINANCIAL/2024/Invoices/240027_Jacob_Langemeier.pdf	yes	7	100	20	2	1	1	\N
194	2023-05-26	2025-05-04	128.00	23002	yes	Leaseville	None	yes	35	100	5	1	2	1	\N
472	2024-05-14	2025-05-04	1311.87	240019	yes	Vegas I	PNC Deposit	yes	7	5	19	3	1	1	\N
360	2023-12-01	2025-05-04	99.38	23002	yes	iPad		yes	35	100	5	1	2	1	\N
477	2024-05-16	2025-05-04	29.40	240033	yes	240033	/Volumes/Business/TSP/_FINANCIAL/2024/Receipts	yes	10	8	26	3	2	1	\N
447	2024-04-30	2025-05-04	251.03	240025	yes	Charlotte I Car	Blaze CC	yes	67	6	23	3	2	1	\N
470	2024-05-13	2025-05-04	109.99	240999	yes	FirstNet		yes	11	100	29	1	2	1	\N
441	2024-04-18	2025-05-04	500.00	240020	yes	Wedding Deposit - Drinkwater	Stripe Payment	yes	7	100	20	2	1	1	\N
457	2024-05-09	2025-05-04	143.61	240999	yes	The Hartford		yes	2	100	8	1	2	1	\N
463	2024-05-13	2025-05-04	74.40	240999	yes	Cell Phone		yes	35	100	3	1	2	1	\N
456	2024-05-08	2025-05-04	251.03	240999	yes	\N	Blaze CC	yes	67	14	23	3	2	1	\N
474	2024-05-16	2025-05-04	5.00	240999	yes	Drone Registration	PNC Debit	yes	3	100	36	3	2	1	\N
629	2024-11-22	2025-05-04	74.40	October	yes	FirstNet Cell Phone Purchase	Posted on the 18th	yes	35	100	3	1	2	1	\N
450	2024-05-06	2025-05-04	248.60	240049	yes	Sonoma Air	PNC Debit	yes	69	14	24	3	2	1	\N
621	2024-11-22	2025-05-04	74.40	August	yes	FirstNet Cell Phone Purchase	Posted on the 18th	yes	35	100	3	1	2	1	\N
451	2024-05-06	2025-05-04	17.99	240049	yes	Sonoma Air	PNC Debit	yes	69	14	24	3	2	1	\N
495	2024-06-05	2025-05-04	2750.00	240033	yes	Chicago	PNC Deposit	yes	7	8	19	3	1	1	\N
452	2024-05-06	2025-05-04	13.99	240049	yes	Sonoma Air	PNC Debit	yes	69	14	24	3	2	1	\N
453	2024-05-06	2025-05-04	68.00	240999	yes	Minnesota	PNC Debit	yes	69	1	24	3	2	1	\N
445	2024-04-29	2025-05-04	11.42	240025	yes	Charlotte I Gas	Blaze CC	yes	69	6	27	3	2	1	\N
446	2024-04-29	2025-05-04	18.94	240025	yes	Charlotte I Gas	Blaze CC	yes	69	6	27	3	2	1	\N
444	2024-04-26	2025-05-04	56.10	240025	yes	Charlotte I Gas	Capital One CC	yes	69	6	27	3	34	1	\N
448	2024-05-01	2025-05-04	42.86	240047	yes	Norwalk - Gas	Capital One CC	yes	69	12	27	3	34	1	\N
476	2024-05-16	2025-05-04	40.05	240033	yes	240033	/Volumes/Business/TSP/_FINANCIAL/2024/Receipts/240031_gas_2.pdf	yes	69	8	27	3	2	1	\N
479	2024-05-20	2025-05-04	50.08	240033	yes		Chase Business Card	yes	69	8	27	3	2	1	\N
480	2024-05-20	2025-05-04	575.36	240033	yes	240033	/volumes/TSP/_FINANCIAL/2024/Receipts/240031_NHRA_Chicago_Hotel.pdf	yes	69	8	25	3	2	1	\N
478	2024-05-20	2025-05-04	338.35	240033	yes	Chicago - Mileage (505 @ .67)	None	yes	69	8	28	3	2	1	\N
499	2024-06-12	2025-05-04	251.03	240039	yes	NHRA Bristol	Capital One - Red	yes	67	10	23	3	2	1	\N
502	2024-06-18	2025-05-04	2750.00	240025	yes	Charlotte I	PNC Deposit	yes	7	6	19	3	1	1	\N
332	2023-10-26	2025-05-04	128.00	23002	yes	Leaseville	None	yes	35	100	5	1	2	1	\N
514	2024-06-26	2025-05-04	251.03	240042	yes	NHRA Virginia	Captal One - Red	yes	67	37	23	3	2	1	\N
529	2024-07-01	2025-05-04	200.82	240047	yes	NHRA Norwalk	240047_Car.pdf	yes	67	12	23	3	2	1	\N
382	2024-01-12	2025-05-04	9.99	240999	yes	Apple iCloud	None	yes	4	100	12	1	2	1	\N
519	2024-07-01	2025-05-04	8.88	240047	yes	NHRA Norwalk	PNC Debit	yes	10	12	26	3	2	1	\N
523	2024-07-01	2025-05-04	29.00	240999	yes	Udemy	PNC Debit	yes	8	100	21	1	2	1	\N
526	2024-07-01	2025-05-04	109.99	240999	yes	FirstNet	PNC Debit	yes	11	100	29	1	2	1	\N
503	2024-06-20	2025-05-04	325.00	240026	yes	Veteran Droners - Crown Hill	Stripe Deposit	yes	7	100	19	3	1	1	\N
319	2023-10-01	2025-05-04	128.00	23002	yes	Leaseville		yes	35	100	5	1	2	1	\N
314	2023-10-01	2025-05-04	13.36	23002	yes	Microsoft 365		yes	4	100	12	1	2	1	\N
528	2024-07-01	2025-05-04	146.31	240999	yes	The Hartford	Chase Debit	yes	2	100	8	1	2	1	\N
106	2023-10-02	2025-05-04	82.08	23002	yes	Samsung		yes	35	100	5	1	2	1	\N
185	2023-05-01	2025-05-04	82.08	23002	yes	Samsung		yes	35	100	5	1	2	1	\N
530	2024-07-05	2025-05-04	3000.00	240039	yes	Bristol Invoice	PNC Deposit	yes	7	10	19	3	1	1	\N
215	2023-06-24	2025-05-04	82.18	23002	yes	Samsung - Monitor	None	yes	35	100	5	1	2	1	\N
380	2024-01-09	2025-05-04	128.00	240999	yes	Leaseville	None	yes	35	100	5	1	2	1	\N
535	2024-07-24	2025-05-04	3000.00	240042	yes	NHRA Virginia	Chase Business	yes	7	37	19	3	1	1	\N
536	2024-07-26	2025-05-04	7.76	240049	yes	NHRA Sonoma	PNC Debit	yes	10	14	26	3	2	1	\N
132	2023-02-01	2025-05-04	13.36	23002	yes	Microsoft 365		yes	4	100	12	1	2	1	\N
541	2024-08-05	2025-05-04	3000.00	240047	yes	NHRA Norwalk	Chase Business	yes	7	12	19	3	35	1	\N
545	2024-08-30	2025-05-04	3000.00	240049	yes	Sonoma Invoice	Chase Deposit	yes	7	14	19	3	1	1	\N
538	2024-07-30	2025-05-04	366.84	240049	yes	NHRA Sonoma	Capital One - Red	yes	67	14	23	3	2	1	\N
426	2024-04-10	2025-05-04	9.99	240999	yes	Apple iCloud		yes	4	100	12	1	2	1	\N
500	2024-06-12	2025-05-04	135.99	240049	yes	NHRA Sonoma	Capital One - Red	yes	69	14	24	3	2	1	\N
515	2024-06-27	2025-05-04	248.18	240051	yes	Brainerd	Credit One Red	yes	69	12	24	3	2	1	\N
527	2024-07-01	2025-05-04	40.75	240049	yes	Sonoma	None	yes	69	14	24	3	2	1	\N
531	2024-07-15	2025-05-04	82.99	240049	yes	NHRA Sonoma	PNC 	yes	69	14	24	3	2	1	\N
532	2024-07-18	2025-05-04	-82.99	240049	yes	NHRA Sonoma - Airfare credit for Seattle	PNC 	yes	69	14	24	3	2	1	\N
498	2024-06-11	2025-05-04	58.15	240026	yes	Travel: Gas	Chase Business Card	yes	69	1	27	3	2	1	\N
505	2024-06-21	2025-05-04	51.75	240042	yes	Travel: Gas	Chase Business Card	yes	69	37	27	3	2	1	\N
506	2024-06-22	2025-05-04	46.95	240042	yes	Virginia - Fuel	Venture Card	yes	69	37	27	3	34	1	\N
509	2024-06-25	2025-05-04	54.25	240042	yes	Virginia - Fuel	Venture Card	yes	69	37	27	3	34	1	\N
510	2024-06-25	2025-05-04	46.95	240047	yes	Travel: Gas	Chase Business Card	yes	69	12	27	3	2	1	\N
512	2024-06-26	2025-05-04	38.85	240047	yes	Travel: Gas	Chase Business Card	yes	69	12	27	3	2	1	\N
504	2024-06-20	2025-05-04	108.66	240042	yes	Richmond	Fortiva CC	yes	69	37	25	3	2	1	\N
497	2024-06-10	2025-05-04	694.46	240039	yes	Bristol Hotel	Blaze CC	yes	69	10	25	3	2	1	\N
508	2024-06-24	2025-05-04	507.00	240042	yes	NHRA Virginia	240042_hotel.pdf	yes	69	37	25	3	2	1	\N
517	2024-06-30	2025-05-04	410.22	240047	yes	NHRA Norwalk	Fortiva	yes	69	12	25	3	2	1	\N
539	2024-07-31	2025-05-04	1112.60	240049	yes	NHRA Sonoma 	Capital One - 5	yes	69	14	25	3	2	1	\N
544	2024-08-21	2025-05-04	1161.00	240051	yes	Brainerd Hotel	Chase Business	yes	69	15	25	3	2	1	\N
548	2024-09-15	2025-05-04	616.98	240053	yes	Reading Hotel	Venture Card	yes	69	17	25	3	2	1	\N
540	2024-08-01	2025-05-04	15.20	240049	yes	NHRA Sonoma - Tolls	Capital One - Red	yes	69	14	28	3	2	1	\N
552	2024-09-20	2025-05-04	3000.00	240051	yes	Brainerd Invoice	Chase Business Dep.	yes	7	15	19	3	1	1	\N
582	2024-11-22	2025-05-04	17.00	October	yes	FirstNet Cellular Service	Posted on the 8th	yes	4	100	14	4	2	1	\N
364	2023-12-01	2025-05-04	13.36	23002	yes	Microsoft 365		yes	4	100	12	1	2	1	\N
389	2024-02-05	2025-05-04	5.00	240999	yes	Gumroad Software	None	yes	4	100	12	1	2	1	\N
562	2024-10-07	2025-05-04	3000.00	240052	yes	Indy invoice	Chase ACH	yes	7	16	19	3	1	1	\N
567	2024-10-16	2025-05-04	3000.00	240053	yes	Reading Invoice	Chase Business Deposit	yes	7	17	19	3	1	1	\N
572	2024-11-04	2025-05-04	3000.00	240054	yes	St Louis	Chase Business Deposit	yes	7	19	19	3	1	1	\N
573	2024-11-14	2025-05-04	3000.00	240056	yes	Dallas Invoice	Chase Deposit	yes	7	20	19	3	1	1	\N
583	2024-11-22	2025-05-04	29.99	July	yes	Udemy Training Subscription	Posted on the 7th	yes	8	100	21	1	2	1	\N
586	2024-11-22	2025-05-04	29.99	October	yes	Udemy Training Subscription	Posted on the 7th	yes	8	100	21	1	2	1	\N
584	2024-11-22	2025-05-04	29.99	August	yes	Udemy Training Subscription	Posted on the 7th	yes	8	100	21	1	2	1	\N
585	2024-11-22	2025-05-04	29.99	September	yes	Udemy Training Subscription	Posted on the 7th	yes	8	100	21	1	2	1	\N
148	2023-03-01	2025-05-04	82.08	23002	yes	Samsung		yes	35	100	5	1	2	1	\N
129	2023-02-01	2025-05-04	74.40	23002	yes	Cell Phone		yes	35	100	3	1	2	1	\N
143	2023-03-01	2025-05-04	74.40	23002	yes	Cell Phone		yes	35	100	3	1	2	1	\N
557	2024-09-26	2025-05-04	166.92	240999	yes	Luggage	Chase Business	yes	35	100	3	1	2	1	\N
496	2024-06-05	2025-05-04	123.56	240999	yes	Harbor Freight - Drone Case	Chase Business Card	yes	35	100	1	3	2	1	\N
511	2024-06-25	2025-05-04	214.19	249999	yes	Avata II Controller	B & H	yes	35	100	1	3	2	1	\N
617	2024-11-22	2025-05-04	74.40	July	yes	FirstNet Cell Phone Purchase	Posted on the 18th	yes	35	100	3	1	2	1	\N
294	2023-09-05	2025-05-04	250.00	23002	yes	Drone Purchase		yes	35	100	1	3	2	1	\N
260	2023-08-01	2025-05-04	74.40	23002	yes	Cell Phone		yes	35	100	3	1	2	1	\N
618	2024-11-22	2025-05-04	99.38	July	yes	FirstNet iPad Purchase	Posted on the 18th	yes	35	100	3	1	2	1	\N
423	2024-04-10	2025-05-04	99.38	240999	yes	iPad		yes	35	100	5	1	2	1	\N
137	2023-02-01	2025-05-04	128.00	23002	yes	Leaseville		yes	35	100	5	1	2	1	\N
208	2023-06-01	2025-05-04	128.00	23002	yes	Leaseville		yes	35	100	5	1	2	1	\N
411	2024-03-21	2025-05-04	82.08	240999	yes	Samsung		yes	35	100	5	1	2	1	\N
429	2024-04-10	2025-05-04	82.08	240999	yes	Samsung		yes	35	100	5	1	2	1	\N
432	2024-04-10	2025-05-04	128.00	240999	yes	Leaseville		yes	35	100	5	1	2	1	\N
657	2025-01-25	2025-05-04	99.38	Monthly	yes	Verizon iPad	Posted on the 7th	yes	35	100	3	1	2	1	\N
316	2023-10-01	2025-05-04	82.08	23002	yes	Samsung		yes	35	100	5	1	2	1	\N
501	2024-06-13	2025-05-04	230.54	240999	yes	DJI RC Pro Controller	Chase Business Card	yes	35	100	1	3	2	1	\N
177	2023-04-26	2025-05-04	128.00	23002	yes	Leaseville	None	yes	35	100	5	1	2	1	\N
553	2024-09-24	2025-05-04	356.74	240053	yes	Reading Car	Roses Card	yes	67	17	23	3	2	1	\N
299	2023-09-16	2025-05-04	13.36	23002	yes	Paddle.net	None	yes	4	100	12	4	2	1	\N
192	2023-05-16	2025-05-04	13.36	23002	yes	Paddle.net	None	yes	4	100	12	4	2	1	\N
176	2023-04-20	2025-05-04	9.99	23002	yes	Apple iCloud	None	yes	4	100	12	1	2	1	\N
560	2024-09-30	2025-05-04	258.59	240054	yes	St Louis Car	Chase Debit	yes	67	19	23	4	2	1	\N
565	2024-10-14	2025-05-04	463.66	240056	yes	Dallas Car Rental	Chase Business Card	yes	67	20	23	3	2	1	\N
569	2024-10-31	2025-05-04	411.88	240057	yes	Vegas II Car	TC Capital One	yes	67	21	23	3	2	1	\N
563	2024-10-08	2025-05-04	581.38	240059	yes	Pomona II Air	Rose & TC Card	yes	69	4	24	3	2	1	\N
564	2024-10-10	2025-05-04	172.44	240058	yes	Pomona II Airfare	Capital One - T	yes	69	4	24	3	2	1	\N
577	2024-11-19	2025-05-04	80.00	240058	yes	Pomona II Checked Bags	Venture Card	yes	69	4	24	3	2	1	\N
555	2024-09-26	2025-05-04	19.36	240054	yes	St Louis	Roses Card	yes	69	19	27	3	2	1	\N
558	2024-09-29	2025-05-04	48.18	240054	yes	St Louis Gas	Venture Card	yes	69	19	27	3	2	1	\N
559	2024-09-29	2025-05-04	33.31	240054	yes	St Louis Gas	Venture Card	yes	69	19	27	3	2	1	\N
576	2024-11-19	2025-05-04	33.23	240058	yes	Pomona II Gas	Venture Card	yes	69	4	27	3	2	1	\N
556	2024-09-26	2025-05-04	445.05	240054	yes	St Louis	Chase Debit	yes	69	19	25	3	2	1	\N
566	2024-10-14	2025-05-04	650.58	240056	yes	Dallas Hotel	Capital One - T	yes	69	20	25	3	2	1	\N
571	2024-11-03	2025-05-04	277.36	240057	yes	Vegas II Hotel	TC Cap1	yes	69	21	25	3	2	1	\N
575	2024-11-18	2025-05-04	844.25	240058	yes	Pomona II Hotel	Roses Card	yes	69	4	25	3	2	1	\N
568	2024-10-22	2025-05-04	23.97	240056	yes	Dallas Tolls	Chase Business	yes	69	20	28	3	2	1	\N
570	2024-11-01	2025-05-04	18.00	240057	yes	Vegas II Parking	Venture Card	yes	69	21	28	3	2	1	\N
655	2025-01-24	2025-05-04	588.36	250001	yes	Gainseville Flight	Venture Card	yes	69	1	24	3	2	1	\N
607	2024-11-22	2025-05-04	21.39	July	yes	Paddle.com Subscription	Posted on the 20th	yes	4	100	12	4	2	1	\N
645	2024-12-06	2025-05-04	13.36	Monthly	yes	Microsoft 365 Subscription	Posted on the 6th	yes	8	100	44	1	2	1	\N
646	2024-12-06	2025-05-04	9.99	Monthly	yes	Apple iCloud 	Posted on the 6th	yes	8	100	44	1	2	1	\N
649	2024-12-18	2025-05-04	29.99	Monthly	yes	Adobe CC Subscription	Posted on the 18th	yes	8	100	44	1	2	1	\N
650	2024-12-20	2025-05-04	21.39	Monthly	yes	Paddle.com Subscription	Posted on the 20th	yes	8	100	44	4	2	1	\N
625	2024-11-22	2025-05-04	74.40	September	yes	FirstNet Cell Phone Purchase	Posted on the 18th	yes	35	100	3	1	2	1	\N
647	2024-12-10	2025-05-04	17.00	Monthly	yes	FirstNet Cellular Service	Posted on the 8th	yes	8	100	34	4	2	1	\N
262	2023-08-01	2025-05-04	9.99	23002	yes	Apple iCloud		yes	4	100	12	1	2	1	\N
323	2023-10-14	2025-05-04	17.00	23002	yes	Website - Heroku	None	yes	4	100	14	4	2	1	\N
623	2024-11-22	2025-05-04	109.00	September	yes	FirstNet Cellular Service	Posted on the 18th	yes	11	100	29	1	2	1	\N
271	2023-08-14	2025-05-04	13.38	23002	yes	Office 365	None	yes	4	100	12	1	2	1	\N
263	2023-08-01	2025-05-04	13.36	23002	yes	Microsoft 365		yes	4	100	12	1	2	1	\N
613	2024-11-22	2025-05-04	144.29	September	yes	Business Insurance	Posted on the 1st	yes	2	100	8	1	2	1	\N
408	2024-03-21	2025-05-04	9.99	240999	yes	Apple iCloud		yes	4	100	12	1	2	1	\N
156	2023-03-14	2025-05-04	13.38	23002	yes	Office 365	None	yes	4	100	12	1	2	1	\N
640	2024-11-26	2025-05-04	3000.00	240057	yes	Vegas II Invoice	Chase Business Deposit	yes	7	100	19	3	1	1	\N
589	2024-11-22	2025-05-04	13.36	August	yes	Microsoft 365 Subscription	Posted on the 6th	yes	4	100	12	1	2	1	\N
127	2023-01-20	2025-05-04	9.99	23002	yes	Apple iCloud	None	yes	4	100	12	1	2	1	\N
124	2023-01-12	2025-05-04	13.38	23002	yes	Office 365	None	yes	4	100	12	1	2	1	\N
522	2024-07-01	2025-05-04	13.36	240999	yes	Microsoft 365	PNC Debit	yes	4	100	12	1	2	1	\N
261	2023-08-01	2025-05-04	29.99	23002	yes	Adobe CC		yes	4	100	12	1	2	1	\N
490	2024-06-01	2025-05-04	17.00	240999	yes	Heroku	PNC Debit	yes	4	100	14	1	2	1	\N
601	2024-11-22	2025-05-04	9.00	September	yes	Chase: PaymentTech	Posted on the 2nd	yes	4	100	11	1	2	1	\N
590	2024-11-22	2025-05-04	9.99	August	yes	Apple iCloud 	Posted on the 6th	yes	4	100	12	1	2	1	\N
119	2023-01-01	2025-05-04	9.99	23002	yes	Apple iCloud		yes	4	100	12	1	2	1	\N
328	2023-10-20	2025-05-04	9.99	23002	yes	Apple iCloud	None	yes	4	100	12	1	2	1	\N
615	2024-11-22	2025-05-04	109.00	July	yes	FirstNet Cellular Service	Posted on the 18th	yes	11	100	29	1	2	1	\N
525	2024-07-01	2025-05-04	17.00	240999	yes	Heroku	PNC Debit	yes	4	100	14	1	2	1	\N
214	2023-06-20	2025-05-04	9.99	23002	yes	Apple iCloud	None	yes	4	100	12	1	2	1	\N
627	2024-11-22	2025-05-04	109.00	October	yes	FirstNet Cellular Service	Posted on the 18th	yes	11	100	29	1	2	1	\N
614	2024-11-22	2025-05-04	144.29	October	yes	Business Insurance	Posted on the 1st	yes	2	100	8	1	2	1	\N
648	2024-12-10	2025-05-04	144.29	Monthly	yes	Business Insurance	Posted on the 1st	yes	2	100	8	1	2	1	\N
338	2023-11-01	2025-05-04	29.99	23002	yes	Adobe CC		yes	4	100	12	1	2	1	\N
202	2023-06-01	2025-05-04	9.99	23002	yes	Apple iCloud		yes	4	100	12	1	2	1	\N
419	2024-03-27	2025-05-04	180.11	240999	yes	Google Ads	Blaze CC	yes	4	100	10	1	34	1	\N
652	2024-12-30	2025-05-04	15.00	Monthly	yes	Chase: Account Fee	Posted on the 30th	yes	4	67	11	1	2	1	\N
653	2024-12-30	2025-05-04	120.00	249999	yes	Smugmug Annual Subscription	Chase Debit	yes	4	67	12	1	2	1	\N
587	2024-11-22	2025-05-04	13.36	July	yes	Microsoft 365 Subscription	Posted on the 6th	yes	4	100	12	1	2	1	\N
611	2024-11-22	2025-05-04	144.29	July	yes	Business Insurance	Posted on the 1st	yes	2	100	8	1	2	1	\N
619	2024-11-22	2025-05-04	109.00	August	yes	FirstNet Cellular Service	Posted on the 18th	yes	11	100	29	1	2	1	\N
612	2024-11-22	2025-05-04	144.29	August	yes	Business Insurance	Posted on the 1st	yes	2	100	8	1	2	1	\N
713	2025-03-27	2025-05-07	35.00	250102	Yes	Phoenix - Indy checked bag	receipts/Screenshot_2025-05-07_at_8.38.21PM.png	Yes	69	2	24	3	2	1	35.00
701	2025-03-25	2025-05-07	433.67	250102	Yes	Phoenix Rental Car		Yes	67	2	23	3	2	1	\N
537	2024-07-29	2025-05-04	142.46	240999	yes	Avata 2 Case	Capital One CC	yes	35	100	1	3	34	1	\N
667	2025-02-02	2025-05-04	99.38	Monthly	yes	Verizon iPad	Posted on the 7th	yes	35	100	3	1	2	1	\N
668	2025-02-02	2025-05-04	13.36	Monthly	yes	Microsoft 365 Subscription	Posted on the 6th	yes	8	100	44	1	2	1	\N
673	2025-02-02	2025-05-04	29.99	Monthly	yes	Adobe CC Subscription	Posted on the 18th	yes	8	100	44	1	2	1	\N
706	2025-03-11	2025-05-07	231.10	250101	Yes	Gainesville car rental	receipts/Screenshot_2025-05-07_at_8.17.47PM.png	Yes	67	1	23	3	2	1	\N
714	2025-04-02	2025-05-07	393.54	250103	Yes	Pomona I Car Rental	receipts/Screenshot_2025-05-07_at_8.40.33PM.png	Yes	67	3	23	3	2	1	\N
702	2025-02-04	2025-05-07	113.58	250102	yes	Phoenix Airfare	receipts/Screenshot_2025-05-07_at_8.09.37PM.png	Yes	69	2	24	3	2	1	\N
703	2025-02-04	2025-05-07	401.97	250102	Yes	Phoenix Flights	receipts/Screenshot_2025-05-07_at_8.10.40PM.png	Yes	69	2	24	3	2	1	\N
670	2025-02-02	2025-05-04	15.00	Monthly	yes	Chase: Account Fee	Posted on the 30th	yes	4	100	11	1	2	1	\N
705	2025-03-10	2025-05-07	34.99	250101	y	Gainesville - Indy checked bag	receipts/Screenshot_2025-05-07_at_8.16.31PM.png	Yes	69	1	24	3	2	1	\N
707	2025-03-11	2025-05-07	35.00	250101	Yes	Indy - Gainesville checked bat	receipts/Screenshot_2025-05-07_at_8.18.57PM.png	Yes	69	1	24	3	2	1	\N
666	2025-02-02	2025-05-04	55.00	Monthly	yes	FirstNet Cellular Service	Posted on the 8th	yes	8	100	34	4	2	1	\N
669	2025-02-02	2025-05-04	9.99	Monthly	yes	Apple iCloud 	Posted on the 6th	yes	8	100	44	1	2	1	\N
710	2025-03-19	2025-05-07	35.00	250102	Yes	Phoenix - Indy Checked bag	receipts/Screenshot_2025-05-07_at_8.22.54PM.png	Yes	69	2	24	3	2	1	\N
694	2023-11-12	2025-05-07	48.06	230024	y	Pomona II Gas		Yes	69	4	27	3	2	1	\N
695	2023-12-01	2025-05-07	31.70	230023	Yes	Vegas II gas		Yes	69	21	27	3	2	1	\N
696	2023-10-15	2025-05-07	31.70	230023	y	Dallas Gas		Yes	69	20	27	3	2	1	\N
697	2023-10-02	2025-05-07	59.25	230021	y	St Louis Gas		Yes	69	19	27	3	2	1	\N
660	2025-01-25	2025-05-04	15.00	Monthly	yes	Chase: Account Fee	Posted on the 30th	yes	4	100	11	1	2	1	\N
698	2023-09-24	2025-05-07	124.00	230021	Y	Charlotte Gas		Yes	69	6	27	3	2	1	\N
662	2025-01-25	2025-05-04	21.39	Monthly	yes	Paddle.com Subscription	Posted on the 20th	yes	8	100	44	4	2	1	\N
659	2025-01-25	2025-05-04	9.99	Monthly	yes	Apple iCloud 	Posted on the 6th	yes	8	100	44	1	2	1	\N
679	2025-02-08	2025-05-04	9.00	Monthly	yes	Chase: PaymentTech	Posted on the 2nd	yes	4	100	11	1	2	1	\N
680	2025-02-09	2025-05-04	15.00	Monthly	yes	Chase: Account Fee	Posted on the 30th	yes	4	100	11	1	2	1	\N
684	2022-03-08	2025-05-04	1400.00	22001	yes	Fatheadz Pay	Check to PNC	yes	7	34	19	3	1	1	\N
699	2023-10-18	2025-05-07	60.19	230019	Yes	Reading gas		Yes	69	17	27	3	2	1	\N
120	2023-01-01	2025-05-04	13.36	23002	yes	Microsoft 365		yes	4	100	12	1	2	1	\N
704	2025-03-07	2025-05-07	37.58	250101	Yes	Gainesville meal	receipts/Screenshot_2025-05-07_at_8.14.55PM.png	Yes	10	1	26	3	2	1	\N
700	2023-07-30	2025-05-07	48.02	230017	y	Sonoma gas		Yes	69	14	27	3	2	1	\N
709	2025-03-11	2025-05-07	30.42	250102	Yes	Gainesville meals	receipts/Screenshot_2025-05-07_at_8.21.37PM.png	Yes	10	1	26	3	2	1	\N
711	2025-03-21	2025-05-07	30.60	250102	Yes	Phoenix meals	receipts/Screenshot_2025-05-07_at_8.24.03PM.png	Yes	10	2	26	3	2	1	\N
712	2025-03-26	2025-05-07	69.92	250102	Yes	Phoenix Gas	receipts/Screenshot_2025-05-07_at_8.36.32PM.png	Yes	69	2	27	3	2	1	\N
663	2025-01-25	2025-05-04	143.61	Monthly	yes	Business Insurance	Posted on the 1st	yes	2	100	8	1	2	1	\N
683	2022-01-23	2025-05-04	36.00	22001	yes	Epping - Parking	Volumes/Business/TSP/_FINANCIAL//2023/2022_Receipts/IMG_0659 3.jpeg	yes	69	9	28	3	2	1	\N
721	2025-04-17	2025-05-07	223.40	250104	Yes	Vegas I Car Rental	receipts/Screenshot_2025-05-07_at_8.51.51PM.png	Yes	67	5	23	3	2	1	\N
717	2025-04-25	2025-05-07	3250.00	250103	Yes	Pomona I Invoice		Yes	7	3	19	3	1	1	\N
718	2025-04-01	2025-05-07	21.07	250103	Yes	Pomona I meals	receipts/Screenshot_2025-05-07_at_8.46.59PM.png	Yes	10	3	26	3	2	1	\N
719	2025-03-31	2025-05-07	14.85	250103	Yes	Pomona I meals	receipts/Screenshot_2025-05-07_at_8.48.07PM.png	Yes	10	3	26	3	2	1	\N
720	2025-04-12	2025-05-07	9.40	250104	Yes	Vegas I Meals	receipts/Screenshot_2025-05-07_at_8.49.52PM.png	Yes	10	5	26	3	2	1	\N
654	2024-12-31	2025-05-04	3000.00	240058	yes	Pomona II Invoice	Chase Dep	yes	7	4	19	3	1	1	\N
723	2025-01-24	2025-05-07	588.36	250101	Yes	Gainesville Flights	receipts/Screenshot_2025-05-07_at_10.09.04PM.png	Yes	69	1	24	3	2	1	\N
715	2025-04-03	2025-05-07	43.20	250103	Yes	Pomona I Gas	receipts/Screenshot_2025-05-07_at_8.42.07PM.png	Yes	69	3	27	3	2	1	\N
412	2024-03-21	2025-05-04	17.00	240999	yes	Heroku		yes	4	100	14	1	2	1	\N
722	2025-04-16	2025-05-07	22.83	250104	Yes	Vegas I Gas	receipts/Screenshot_2025-05-07_at_8.53.10PM.png	Yes	69	5	27	3	2	1	\N
578	2024-11-20	2025-05-04	234.95	I281919	yes	InkOwl Pro 2000 Ink	Chase Business Debit	yes	4	100	13	2	2	1	\N
610	2024-11-22	2025-05-04	21.39	October	yes	Paddle.com Subscription	Posted on the 20th	yes	4	100	12	4	2	1	\N
592	2024-11-22	2025-05-04	9.99	September	yes	Apple iCloud 	Posted on the 6th	yes	4	100	12	1	2	1	\N
579	2024-11-22	2025-05-04	17.00	July	yes	FirstNet Cellular Service	Posted on the 8th	yes	4	100	14	4	2	1	\N
298	2023-09-14	2025-05-04	13.38	23002	yes	Office 365	None	yes	4	100	12	1	2	1	\N
244	2023-07-16	2025-05-04	13.36	23002	yes	Paddle.net	None	yes	4	100	12	4	2	1	\N
232	2023-07-01	2025-05-04	9.99	23002	yes	Apple iCloud		yes	4	100	12	1	2	1	\N
644	2024-12-02	2025-05-04	9.00	Monthly	yes	Chase: PaymentTech	Posted on the 2nd	yes	4	100	11	1	2	1	\N
602	2024-11-22	2025-05-04	9.00	October	yes	Chase: PaymentTech	Posted on the 2nd	yes	4	100	11	1	2	1	\N
302	2023-09-20	2025-05-04	9.99	23002	yes	Apple iCloud	None	yes	4	100	12	1	2	1	\N
409	2024-03-21	2025-05-04	13.36	240999	yes	Microsoft 365		yes	4	100	12	1	2	1	\N
288	2023-09-01	2025-05-04	17.00	23002	yes	Heroku		yes	4	100	14	1	2	1	\N
521	2024-07-01	2025-05-04	9.99	240999	yes	Apple iCloud	PNC Debit	yes	4	100	12	1	2	1	\N
131	2023-02-01	2025-05-04	9.99	23002	yes	Apple iCloud		yes	4	100	12	1	2	1	\N
324	2023-10-14	2025-05-04	13.38	23002	yes	Office 365	None	yes	4	100	12	1	2	1	\N
212	2023-06-16	2025-05-04	13.36	23002	yes	Paddle.net	None	yes	4	100	12	4	2	1	\N
599	2024-11-22	2025-05-04	9.00	July	yes	Chase: PaymentTech	Posted on the 2nd	yes	4	100	11	1	2	1	\N
353	2023-11-16	2025-05-04	13.36	23002	yes	Paddle.net	None	yes	4	100	12	4	2	1	\N
165	2023-04-01	2025-05-04	13.36	23002	yes	Microsoft 365		yes	4	100	12	1	2	1	\N
427	2024-04-10	2025-05-04	13.36	240999	yes	Microsoft 365		yes	4	100	12	1	2	1	\N
639	2024-11-25	2025-05-04	117.49	249999	yes	24x100 Photo Paper Breathing Color	Chase	yes	4	100	13	2	2	1	\N
283	2023-09-01	2025-05-04	29.99	23002	yes	Adobe CC		yes	4	100	12	1	2	1	\N
624	2024-11-22	2025-05-04	29.99	September	yes	Adobe CC Subscription	Posted on the 18th	yes	4	100	12	1	2	1	\N
620	2024-11-22	2025-05-04	29.99	August	yes	Adobe CC Subscription	Posted on the 18th	yes	4	100	12	1	2	1	\N
616	2024-11-22	2025-05-04	29.99	July	yes	Adobe CC Subscription	Posted on the 18th	yes	4	100	12	1	2	1	\N
297	2023-09-14	2025-05-04	17.00	23002	yes	Website - Heroku	None	yes	4	100	14	4	2	1	\N
181	2023-05-01	2025-05-04	29.99	23002	yes	Adobe CC		yes	4	100	12	1	2	1	\N
245	2023-07-20	2025-05-04	9.99	23002	yes	Apple iCloud	None	yes	4	100	12	1	2	1	\N
466	2024-05-13	2025-05-04	13.36	240999	yes	Microsoft 365		yes	4	100	12	1	2	1	\N
407	2024-03-21	2025-05-04	29.99	240999	yes	Adobe CC		yes	4	100	12	1	2	1	\N
201	2023-06-01	2025-05-04	29.99	23002	yes	Adobe CC		yes	4	100	12	1	2	1	\N
325	2023-10-16	2025-05-04	13.36	23002	yes	Paddle.net	None	yes	4	100	12	4	2	1	\N
395	2024-02-14	2025-05-04	17.00	240999	yes	Website - Heroku	None	yes	4	100	14	1	2	1	\N
174	2023-04-14	2025-05-04	13.38	23002	yes	Office 365	None	yes	4	100	12	1	2	1	\N
643	2024-11-27	2025-05-04	71.88	249999	yes	Siteground Hosting Annual	Chase	yes	4	100	12	4	2	1	\N
233	2023-07-01	2025-05-04	13.36	23002	yes	Microsoft 365		yes	4	100	12	1	2	1	\N
144	2023-03-01	2025-05-04	29.99	23002	yes	Adobe CC		yes	4	100	12	1	2	1	\N
400	2024-02-22	2025-05-04	13.36	240999	yes	Paddle.Net	None	yes	4	100	12	1	2	1	\N
163	2023-04-01	2025-05-04	29.99	23002	yes	Adobe CC		yes	4	100	12	1	2	1	\N
598	2024-11-22	2025-05-04	15.00	October	yes	Chase: Account Fee	Posted on the 30th	yes	4	100	11	1	2	1	\N
373	2023-12-16	2025-05-04	13.36	23002	yes	Paddle.net	None	yes	4	100	12	4	2	1	\N
241	2023-07-13	2025-05-04	32.16	23002	yes	GoDaddy Domain Renewal	None	yes	4	100	12	34	2	1	\N
175	2023-04-16	2025-05-04	13.36	23002	yes	Paddle.net	None	yes	4	100	12	4	2	1	\N
393	2024-02-12	2025-05-04	9.99	240999	yes	Apple iCloud	None	yes	4	100	12	1	2	1	\N
363	2023-12-01	2025-05-04	9.99	23002	yes	Apple iCloud		yes	4	100	12	1	2	1	\N
343	2023-11-01	2025-05-04	17.00	23002	yes	Heroku		yes	4	100	14	1	2	1	\N
596	2024-11-22	2025-05-04	15.00	August	yes	Chase: Account Fee	Posted on the 30th	yes	4	100	11	1	2	1	\N
362	2023-12-01	2025-05-04	29.99	23002	yes	Adobe CC		yes	4	100	12	1	2	1	\N
285	2023-09-01	2025-05-04	13.36	23002	yes	Microsoft 365		yes	4	100	12	1	2	1	\N
464	2024-05-13	2025-05-04	29.99	240999	yes	Adobe CC		yes	4	100	12	1	2	1	\N
430	2024-04-10	2025-05-04	17.00	240999	yes	Heroku		yes	4	100	14	1	2	1	\N
581	2024-11-22	2025-05-04	17.00	September	yes	FirstNet Cellular Service	Posted on the 8th	yes	4	100	14	4	2	1	\N
312	2023-10-01	2025-05-04	29.99	23002	yes	Adobe CC		yes	4	100	12	1	2	1	\N
231	2023-07-01	2025-05-04	29.99	23002	yes	Adobe CC		yes	4	100	12	1	2	1	\N
661	2025-01-25	2025-05-04	9.00	Monthly	yes	Chase: PaymentTech	Posted on the 2nd	yes	4	100	11	1	2	1	\N
340	2023-11-01	2025-05-04	13.36	23002	yes	Microsoft 365		yes	4	100	12	1	2	1	\N
158	2023-03-20	2025-05-04	9.99	23002	yes	Apple iCloud	None	yes	4	100	12	1	2	1	\N
594	2024-11-22	2025-05-04	9.99	October	yes	Apple iCloud 	Posted on the 6th	yes	4	100	12	1	2	1	\N
469	2024-05-13	2025-05-04	17.00	240999	yes	Heroku		yes	4	100	14	1	2	1	\N
533	2024-07-19	2025-05-04	35.16	240999	yes	GoDaddy Domain Renewal	PNC Debit	yes	4	100	12	4	2	1	\N
118	2023-01-01	2025-05-04	29.99	23002	yes	Adobe CC		yes	4	100	12	1	2	1	\N
609	2024-11-22	2025-05-04	21.39	September	yes	Paddle.com Subscription	Posted on the 20th	yes	4	100	12	4	2	1	\N
608	2024-11-22	2025-05-04	21.39	August	yes	Paddle.com Subscription	Posted on the 20th	yes	4	100	12	4	2	1	\N
317	2023-10-01	2025-05-04	17.00	23002	yes	Heroku		yes	4	100	14	1	2	1	\N
284	2023-09-01	2025-05-04	9.99	23002	yes	Apple iCloud		yes	4	100	12	1	2	1	\N
487	2024-06-01	2025-05-04	13.36	240999	yes	Microsoft 365	PNC Debit	yes	4	100	12	1	2	1	\N
458	2024-05-09	2025-05-04	6.08	240027	yes	Senior Portraits - Langemeier		yes	4	100	38	2	2	1	\N
372	2023-12-14	2025-05-04	13.38	23002	yes	Office 365	None	yes	4	100	12	1	2	1	\N
126	2023-01-16	2025-05-04	13.36	23002	yes	Paddle.net	None	yes	4	100	12	4	2	1	\N
339	2023-11-01	2025-05-04	9.99	23002	yes	Apple iCloud		yes	4	100	12	1	2	1	\N
600	2024-11-22	2025-05-04	9.00	August	yes	Chase: PaymentTech	Posted on the 2nd	yes	4	100	11	1	2	1	\N
243	2023-07-14	2025-05-04	13.38	23002	yes	Office 365	None	yes	4	100	12	1	2	1	\N
595	2024-11-22	2025-05-04	15.00	July	yes	Chase: Account Fee	Posted on the 30th	yes	4	100	11	1	2	1	\N
385	2024-01-22	2025-05-04	13.36	240999	yes	Paddle.Net	None	yes	4	100	12	1	2	1	\N
371	2023-12-14	2025-05-04	17.00	23002	yes	Website - Heroku	None	yes	4	100	14	4	2	1	\N
367	2023-12-01	2025-05-04	17.00	23002	yes	Heroku		yes	4	100	14	1	2	1	\N
374	2023-12-20	2025-05-04	9.99	23002	yes	Apple iCloud	None	yes	4	100	12	1	2	1	\N
588	2024-11-22	2025-05-04	9.99	July	yes	Apple iCloud 	Posted on the 6th	yes	4	100	12	1	2	1	\N
534	2024-07-19	2025-05-04	22.17	240999	yes	GoDaddy Domain Renewal	PNC Debit	yes	4	100	12	4	2	1	\N
591	2024-11-22	2025-05-04	13.36	September	yes	Microsoft 365 Subscription	Posted on the 6th	yes	4	100	12	1	2	1	\N
157	2023-03-16	2025-05-04	13.36	23002	yes	Paddle.net	None	yes	4	100	12	4	2	1	\N
651	2024-12-23	2025-05-04	25.16	249999	yes	Google Suite	Chase	yes	4	100	12	1	2	1	\N
381	2024-01-12	2025-05-04	13.38	240999	yes	Office 365	None	yes	4	100	12	1	2	1	\N
183	2023-05-01	2025-05-04	13.36	23002	yes	Microsoft 365		yes	4	100	12	1	2	1	\N
313	2023-10-01	2025-05-04	9.99	23002	yes	Apple iCloud		yes	4	100	12	1	2	1	\N
597	2024-11-22	2025-05-04	15.00	September	yes	Chase: Account Fee	Posted on the 30th	yes	4	100	11	1	2	1	\N
442	2024-04-18	2025-05-04	14.80	240020	yes	Drinkwater Wedding	Stripe fee for Drinkwater Wedding Deposit	yes	4	100	38	2	2	1	\N
354	2023-11-20	2025-05-04	9.99	23002	yes	Apple iCloud	None	yes	4	100	12	1	2	1	\N
140	2023-02-16	2025-05-04	13.36	23002	yes	Paddle.net	None	yes	4	100	12	4	2	1	\N
139	2023-02-14	2025-05-04	13.38	23002	yes	Office 365	None	yes	4	100	12	1	2	1	\N
193	2023-05-20	2025-05-04	9.99	23002	yes	Apple iCloud	None	yes	4	100	12	1	2	1	\N
593	2024-11-22	2025-05-04	13.36	October	yes	Microsoft 365 Subscription	Posted on the 6th	yes	4	100	12	1	2	1	\N
164	2023-04-01	2025-05-04	9.99	23002	yes	Apple iCloud		yes	4	100	12	1	2	1	\N
392	2024-02-12	2025-05-04	13.38	240999	yes	Office 365	None	yes	4	100	12	1	2	1	\N
191	2023-05-14	2025-05-04	13.38	23002	yes	Office 365	None	yes	4	100	12	1	2	1	\N
425	2024-04-10	2025-05-04	29.99	240999	yes	Adobe CC		yes	4	100	12	1	2	1	\N
141	2023-02-20	2025-05-04	9.99	23002	yes	Apple iCloud	None	yes	4	100	12	1	2	1	\N
211	2023-06-14	2025-05-04	13.38	23002	yes	Office 365	None	yes	4	100	12	1	2	1	\N
671	2025-02-02	2025-05-04	9.00	Monthly	yes	Chase: PaymentTech	Posted on the 2nd	yes	4	100	11	1	2	1	\N
580	2024-11-22	2025-05-04	17.00	August	yes	FirstNet Cellular Service	Posted on the 8th	yes	4	100	14	4	2	1	\N
628	2024-11-22	2025-05-04	29.99	October	yes	Adobe CC Subscription	Posted on the 18th	yes	4	100	12	1	2	1	\N
182	2023-05-01	2025-05-04	9.99	23002	yes	Apple iCloud		yes	4	100	12	1	2	1	\N
465	2024-05-13	2025-05-04	9.99	240999	yes	Apple iCloud		yes	4	100	12	1	2	1	\N
449	2024-05-04	2025-05-04	54.00	240999	yes	PS & LR Editing software	Email	yes	4	100	12	2	2	1	\N
520	2024-07-01	2025-05-04	29.99	240999	yes	Adobe CC	PNC Debit	yes	4	100	12	1	2	1	\N
145	2023-03-01	2025-05-04	9.99	23002	yes	Apple iCloud		yes	4	100	12	1	2	1	\N
130	2023-02-01	2025-05-04	29.99	23002	yes	Adobe CC		yes	4	100	12	1	2	1	\N
270	2023-08-14	2025-05-04	17.00	23002	yes	Website - Heroku	None	yes	4	100	14	4	2	1	\N
486	2024-06-01	2025-05-04	9.99	240999	yes	Apple iCloud	PNC Debit	yes	4	100	12	1	2	1	\N
203	2023-06-01	2025-05-04	13.36	23002	yes	Microsoft 365		yes	4	100	12	1	2	1	\N
665	2025-02-02	2025-05-04	55.00	Monthly	yes	FirstNet Cellular Service	Posted on the 8th	yes	8	100	34	4	2	1	\N
674	2025-02-03	2025-05-04	13.36	Monthly	yes	Microsoft 365 Subscription	Posted on the 6th	yes	8	100	44	1	2	1	\N
676	2025-02-05	2025-05-04	29.99	Monthly	yes	Adobe CC Subscription	Posted on the 18th	yes	8	100	44	1	2	1	\N
658	2025-01-25	2025-05-04	13.36	Monthly	yes	Microsoft 365 Subscription	Posted on the 6th	yes	8	100	44	1	2	1	\N
664	2025-01-25	2025-05-04	29.99	Monthly	yes	Adobe CC Subscription	Posted on the 18th	yes	8	100	44	1	2	1	\N
656	2025-01-25	2025-05-04	17.00	Monthly	yes	FirstNet Cellular Service	Posted on the 8th	yes	8	100	34	4	2	1	\N
678	2025-02-07	2025-05-04	21.39	Monthly	yes	Paddle.com Subscription	Posted on the 20th	yes	8	100	44	4	2	1	\N
672	2025-02-02	2025-05-04	21.39	Monthly	yes	Paddle.com Subscription	Posted on the 20th	yes	8	100	44	4	2	1	\N
675	2025-02-04	2025-05-04	9.99	Monthly	yes	Apple iCloud 	Posted on the 6th	yes	8	100	44	1	2	1	\N
142	2023-03-01	2025-05-04	99.38	23002	yes	iPad		yes	35	100	5	1	2	1	\N
492	2024-06-01	2025-05-04	128.00	240999	yes	Leaseville	PNC Debit	yes	35	100	5	1	2	1	\N
439	2024-04-16	2025-05-04	74.85	240999	yes	Camera Neck Strap - Roberts	/volumes/TSP/_FINANCIAL/2024/Receipts/camera_strap.pdf	yes	35	100	4	2	2	1	\N
637	2024-11-22	2025-05-04	128.00	September	yes	Computer Speakers/Lights	Posted on the 11th & 13th	yes	35	100	5	1	2	1	\N
355	2023-11-24	2025-05-04	82.18	23002	yes	Samsung - Monitor	None	yes	35	100	5	1	2	1	\N
224	2023-06-28	2025-05-04	250.00	23002	yes	Drone Purchase		yes	35	100	1	3	2	1	\N
603	2024-11-22	2025-05-04	82.18	July	yes	Samsung Monitor - Affirm	Posted on the 24th	yes	35	100	5	4	2	1	\N
336	2023-11-01	2025-05-04	99.38	23002	yes	iPad		yes	35	100	5	1	2	1	\N
230	2023-07-01	2025-05-04	74.40	23002	yes	Cell Phone		yes	35	100	3	1	2	1	\N
606	2024-11-22	2025-05-04	82.18	October	yes	Samsung Monitor - Affirm	Posted on the 24th	yes	35	100	5	4	2	1	\N
301	2023-09-19	2025-05-04	250.00	23002	yes	Drone Purchase		yes	35	100	1	3	2	1	\N
275	2023-08-23	2025-05-04	250.00	23002	yes	Drone Purchase		yes	35	100	1	3	2	1	\N
\.


--
-- Name: finance_transaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.finance_transaction_id_seq', 726, true);


--
-- Name: finance_transaction finance_transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.finance_transaction
    ADD CONSTRAINT finance_transaction_pkey PRIMARY KEY (id);


--
-- Name: finance_transaction_category_id_f48294d6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX finance_transaction_category_id_f48294d6 ON public.finance_transaction USING btree (category_id);


--
-- Name: finance_transaction_keyword_id_6e7ffdff; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX finance_transaction_keyword_id_6e7ffdff ON public.finance_transaction USING btree (keyword_id);


--
-- Name: finance_transaction_sub_cat_id_af30fdfc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX finance_transaction_sub_cat_id_af30fdfc ON public.finance_transaction USING btree (sub_cat_id);


--
-- Name: finance_transaction_team_id_a57f0297; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX finance_transaction_team_id_a57f0297 ON public.finance_transaction USING btree (team_id);


--
-- Name: finance_transaction_trans_type_id_66b14c5e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX finance_transaction_trans_type_id_66b14c5e ON public.finance_transaction USING btree (trans_type_id);


--
-- Name: finance_transaction_user_id_6c085a0b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX finance_transaction_user_id_6c085a0b ON public.finance_transaction USING btree (user_id);


--
-- Name: finance_transaction finance_transaction_category_id_f48294d6_fk_finance_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.finance_transaction
    ADD CONSTRAINT finance_transaction_category_id_f48294d6_fk_finance_category_id FOREIGN KEY (category_id) REFERENCES public.finance_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finance_transaction finance_transaction_keyword_id_6e7ffdff_fk_finance_keyword_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.finance_transaction
    ADD CONSTRAINT finance_transaction_keyword_id_6e7ffdff_fk_finance_keyword_id FOREIGN KEY (keyword_id) REFERENCES public.finance_keyword(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finance_transaction finance_transaction_sub_cat_id_af30fdfc_fk_finance_s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.finance_transaction
    ADD CONSTRAINT finance_transaction_sub_cat_id_af30fdfc_fk_finance_s FOREIGN KEY (sub_cat_id) REFERENCES public.finance_subcategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finance_transaction finance_transaction_team_id_a57f0297_fk_finance_team_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.finance_transaction
    ADD CONSTRAINT finance_transaction_team_id_a57f0297_fk_finance_team_id FOREIGN KEY (team_id) REFERENCES public.finance_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finance_transaction finance_transaction_trans_type_id_66b14c5e_fk_finance_type_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.finance_transaction
    ADD CONSTRAINT finance_transaction_trans_type_id_66b14c5e_fk_finance_type_id FOREIGN KEY (trans_type_id) REFERENCES public.finance_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finance_transaction finance_transaction_user_id_6c085a0b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.finance_transaction
    ADD CONSTRAINT finance_transaction_user_id_6c085a0b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

