# Generated by Django 4.2.20 on 2025-07-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='model',
            field=models.CharField(choices=[('Air 3S', 'Air 3s'), ('Avata 2', 'Avata 2'), ('Mavic 3 Pro', 'Mavic 3 Pro'), ('Mavic 3 Classic', 'Mavic 3 Classic'), ('Air 2S', 'Air 2S'), ('Mini 3 Pro', 'Mini 3 Pro'), ('Inspire 2', 'Inspire 2'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
