# Generated by Django 4.2.20 on 2025-07-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the original purchase cost of the equipment.', max_digits=10, null=True),
        ),
    ]
