# Generated by Django 4.2.20 on 2025-07-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_alter_drone_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightlog',
            old_name='flight_app',
            new_name='flight_application',
        ),
    ]
