# Generated by Django 4.2.20 on 2025-07-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_rename_flight_app_flightlog_flight_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='date_purchased',
        ),
        migrations.AddField(
            model_name='equipment',
            name='date_disposed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('Drone', 'Drone'), ('Battery', 'Battery'), ('Controller', 'Controller'), ('Charger', 'Charger'), ('Accessory', 'Accessory'), ('Other', 'Other')], default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='faa_registration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
