# Generated by Django 4.2.20 on 2025-05-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldocument',
            name='category',
            field=models.CharField(choices=[('Insurance', 'Insurance'), ('FAA', 'FAA Waivers'), ('Registrations', 'Drone Registrations'), ('Event', 'Event Instructions'), ('Policies', 'Policies'), ('Compliance', 'Compliance'), ('Legal', 'Legal'), ('Other', 'Other')], max_length=50),
        ),
    ]
